---
title             : "_Light Exposure Behavior Assessment (LEBA)_: Long and Short Form"
shorttitle        : "LEBA"

author: 
  - name          : "Mushfiqul Anwar Siraji"
    affiliation   : "*"
  - name          : "Rafael Robert Lazar"
    affiliation   : "*"
  - name          : "Juliëtte	van Duijnhoven"
  - name          : "Luc Schlangen"
  - name          : "Shamsul Haque"
  - name          : "Vineetha Kalavally"
  - name          : "Céline Vetter"
  - name          : "Gena Glickman"
  - name          : "Karin Smolders"
  - name          : "Manuel Spitschan"
    affiliation   : "**"

affiliation:
  - id            : "*"
    institution   : "Joint first authors"
  - id            : "**"
    institution   : "Corresponding author: manuel.spitschan@psy.ox.ac.uk"

floatsintext      : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no
documentclass     : "apa6"
classoption       : "man"
output            : 
  papaja::apa6_pdf:
    latex_engine: xelatex
    includes:
      in_header: header.tex
    
mainfont: Helvetica
---

```{r include=FALSE}
library(Hmisc)
knitr::opts_chunk$set(warning = F, error = F, message = F, echo=FALSE)
data <- readRDS("leba_2021-09-08.rds")
sem.data <- data[, 9:56] 
prefix <- "item"
sufix <- c(1:48)
colnam <- paste(prefix,sufix, sep = "" )
colnames(sem.data) <- colnam
```

**Disclaimer**: This is a non-public version of LEBA (dated \today) and still a work in progress. Please do not distribute!

LEBA captures light exposure-related behaviours on a 5 point Likert type scale ranging from 1 to 5 (Never/Does not apply/I don't know = 1; Rarely = 2; Sometimes = 3; Often = 4; Always = 5). The score of each factor is calculated by the summation of scores of items belonging to the corresponding factor. The following instruction is given before displaying the items: "Please indicate how often you performed the following behaviours in the past 4 weeks."

\newpage

\blandscape

# LEBA Long Form (23 Items)

|     | Items                      | Never/Does not apply/I don't know | Rarely | Sometimes | Often | Always |
|-----|----------------------------|-----------------------------------|--------|-----------|-------|--------|
| 1   | `r label(sem.data$item16)` |                                   |        |           |       |        |
| 2   | `r label(sem.data$item17)` |                                   |        |           |       |        |
| 3   | `r label(sem.data$item36)` |                                   |        |           |       |        |
| 4   | `r label(sem.data$item8)`  |                                   |        |           |       |        |
| 5   | `r label(sem.data$item10)` |                                   |        |           |       |        |
| 6   | `r label(sem.data$item9)`  |                                   |        |           |       |        |
| 7   | `r label(sem.data$item11)` |                                   |        |           |       |        |
| 8   | `r label(sem.data$item12)` |                                   |        |           |       |        |
| 9   | `r label(sem.data$item7)`  |                                   |        |           |       |        |
| 10  | `r label(sem.data$item27)` |                                   |        |           |       |        |
| 11  | `r label(sem.data$item3)`  |                                   |        |           |       |        |
| 12  | `r label(sem.data$item40)` |                                   |        |           |       |        |
| 13  | `r label(sem.data$item30)` |                                   |        |           |       |        |
| 14  | `r label(sem.data$item41)` |                                   |        |           |       |        |
| 15  | `r label(sem.data$item32)` |                                   |        |           |       |        |
| 16  | `r label(sem.data$item35)` |                                   |        |           |       |        |
| 17  | `r label(sem.data$item38)` |                                   |        |           |       |        |
| 18  | `r label(sem.data$item33)` |                                   |        |           |       |        |
| 19  | `r label(sem.data$item46)` |                                   |        |           |       |        |
| 20  | `r label(sem.data$item45)` |                                   |        |           |       |        |
| 21  | `r label(sem.data$item25)` |                                   |        |           |       |        |
| 22  | `r label(sem.data$item4)`  |                                   |        |           |       |        |
| 23  | `r label(sem.data$item1)`  |                                   |        |           |       |        |

\elandscape

\newpage

\blandscape

## Latent Structure, Reliability and Structural Validity

The long form of LEBA consists 23 items with five factors.

| Factor names                                          | Items                    | Reliability Coefficients |
|-------------------------------------------------------|--------------------------|--------------------------|
| **F1: Wearing blue light filters**                    | 1-3                      | .93                      |
| **F2: Spending time outdoors**                        | 4-9 (Item 4 is reversed) | .80                      |
| **F3: Using phone and smartwatch in bed**             | 10-14                    | .61                      |
| **F4: Using light before bedtime**                    | 15-18                    | .72                      |
| **F5: Using light in the morning and during daytime** | 19-23                    | .45                      |

LEBA -long form showed satisfactory structural validity (CFI =.97; TLI = .96; RMSEA = .05[.04-.06, 90% CI]; SRMR = .09).

## How to cite:

\elandscape

\newpage

\blandscape

# LEBA Short Form (17 Items)

|     | Short Form (17 Items)      | Never/Does not apply/I don't know | Rarely | Sometimes | Often | Always |
|-----|----------------------------|-----------------------------------|--------|-----------|-------|--------|
| 01  | `r label(sem.data$item16)` |                                   |        |           |       |        |
| 02  | `r label(sem.data$item17)` |                                   |        |           |       |        |
| 03  | `r label(sem.data$item36)` |                                   |        |           |       |        |
| 04  | `r label(sem.data$item8)`  |                                   |        |           |       |        |
| 05  | `r label(sem.data$item10)` |                                   |        |           |       |        |
| 06  | `r label(sem.data$item11)` |                                   |        |           |       |        |
| 07  | `r label(sem.data$item12)` |                                   |        |           |       |        |
| 08  | `r label(sem.data$item7)`  |                                   |        |           |       |        |
| 09  | `r label(sem.data$item27)` |                                   |        |           |       |        |
| 10  | `r label(sem.data$item3)`  |                                   |        |           |       |        |
| 11  | `r label(sem.data$item40)` |                                   |        |           |       |        |
| 12  | `r label(sem.data$item32)` |                                   |        |           |       |        |
| 13  | `r label(sem.data$item35)` |                                   |        |           |       |        |
| 14  | `r label(sem.data$item33)` |                                   |        |           |       |        |
| 15  | `r label(sem.data$item46)` |                                   |        |           |       |        |
| 16  | `r label(sem.data$item45)` |                                   |        |           |       |        |
| 17  | `r label(sem.data$item4)`  |                                   |        |           |       |        |

\elandscape

\newpage

\blandscape

## Latent Structure, Reliability and Structural Validity

The short form of LEBA consists 23 items with five factors.

| Factor names                                          | Items                    |
|-------------------------------------------------------|--------------------------|
| **F1: Wearing blue light filters**                    | 1-3                      |
| **F2: Spending time outdoors**                        | 4-8 (Item 4 is reversed) |
| **F3: Using phone and smartwatch in bed**             | 9-11                     |
| **F4: Using light before bedtime**                    | 12-14                    |
| **F5: Using light in the morning and during daytime** | 15-17                    |

## How to cite:

\elandscape
