---
title             : "_Light Exposure Behavior Assessment (LEBA)_: Develop of a novel instrument to capture light exposure-related behaviours"
shorttitle        : "Title"

author: 
  - name          : "Mushfiqul Anwar Siraji"
    affiliation   : "1"
    corresponding : no   
    address       : "Monash University, Malaysia"
    email         : "mushfiqul.anwarsiraji@monash.edu"
    role:         
      - Data Analysis
      - Writing - Original Draft Preparation
      - Data Visualization
       
  - name          : "Rafael Robert Lazar"
    affiliation   : "2"
    role:
      - Data Analysis
      - Writing - Original Draft Preparation
      - Data Visualization
  - name          : "Manuel Spitschan "
    affiliation   : "3"
    corresponding : yes   
    address       : ""
    email         : ""
    role:         
      - Data Analysis
      - Writing - Original Draft Preparation
      - Data Visualization

affiliation:
  - id            : "1"
    institution   : "Department of Psychology, Jeffrey Cheah School of Medicine and Health Sciences, Monash University, Malaysia"
  - id            : "2"
    institution   : "University of Basel"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library(papaja) # devtools::install_github("crsh/papaja")
library(readr)
library(readxl)
library(lavaan)
library(semPlot)
library(semTools)
library(hemp) # devtools::install_github("cddesja/hemp")
library(psych)
library(dlookr)
library(tidyverse)
library(qgraph)
library(kableExtra)
r_refs("r-references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```
# Introduction

# Methods


## Participants

This line is just a test for pushing in the github repo.

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Confirmatory Factor Analysis
# Confirmatory Factor Analysis

```{r CFA 23 items, include=FALSE}
LB.cfa <- read_excel("recoded not reversed_CFA.xlsx")
LB.model.Cor <- "F1 =~ item5 + item24 + item30 + item1 + item16 + item28
             F2 =~ item10 + item47 + item36 + item44 + item35 + item13
            F3 =~ item43 + item26 + item32
           F4 =~  item14 + item41+ item7 + item27 + item21
            F5 =~ item19 + item34 + item2" 



fit.Cor <- cfa(LB.model.Cor, data = LB.cfa, estimator = "MLR", mimic = "Mplus") 

## Summary of Model 
summary(fit.Cor, fit.measures =TRUE,standardized = TRUE, rsq =TRUE)


## Selected Fit measures 
fit.1 <- fitmeasures (fit.Cor,c("gfi", "agfi", "nfi","rfi", 
                       "cfi.robust","tli.robust",
                       "rmsea.robust", 
                       "srmr","aic"))


semTools::reliability(fit.Cor)

```

```{r CFA23withMI, include=FALSE}
LB.model.Cor.3 <- "F1 =~ item5 + item24 + item30 + item1 + item16 + item28
             F2 =~ item10 + item47 + item36 + item44 + item35 + item13
            F3 =~ item43 + item26 + item32
           F4 =~  item14 + item41+ item7 + item27 + item21
            F5 =~ item19 + item34 + item2
item44 ~~ item13
item14 ~~  item7
item10 ~~ item13" 





## Fit the model 
fit.Cor.3 <- cfa(LB.model.Cor.3, data = LB.cfa, estimator = "MLR", mimic = "Mplus") 

reliability <- semTools::reliability(fit.Cor.3, return.total = T)
as.table(reliability)
## Summary of Model 
summary(fit.Cor.3, fit.measures =TRUE,standardized = TRUE, rsq =TRUE)



## Selected Fit measures 
fit.3 <- fitmeasures (fit.Cor.3,c("gfi", "agfi", "nfi","rfi", 
                       "cfi.robust","tli.robust",
                       "rmsea.robust", 
                       "srmr","aic"))

rownames <-  ("fitIndices")
colnames <- c("gfi", "agfi", "nfi","rfi", 
                       "cfi.robust","tli.robust",
                       "rmsea.robust", 
                       "srmr","aic")


```

```{r CFI18items, include=FALSE}
LB.model.Cor.2 <- "F1 =~ item5 + item24 + item30 + item16 
             F2 =~ item10 + item47 + item36 + item44 + item35 
            F3 =~ item43 + item26 + item32
           F4 =~  item14 + item41+ item7 
            F5 =~ item19 + item34 + item2
item14 ~~  item7" 

#item 1 &28 discarded from F1;
#item13 discarded from F2
#item 27 & 21 discarded from F4

## Fit the model 
fit.Cor.2 <- cfa(LB.model.Cor.2, data = LB.cfa, estimator = "MLR", mimic = "Mplus") 

## Summary of Model 
summary(fit.Cor.2, fit.measures =TRUE,standardized = TRUE, rsq =TRUE)


## Selected Fit measures 
fit.2 <- fitmeasures (fit.Cor.2,c("gfi", "agfi", "nfi","rfi", 
                       "cfi.robust","tli.robust",
                       "rmsea.robust", 
                       "srmr","aic"))

rownames <-  ("fitIndices")
colnames <- c("gfi", "agfi", "nfi","rfi", 
                       "cfi.robust","tli.robust",
                       "rmsea.robust", 
                       "srmr","aic")



```




# Discussion


\newpage
# References

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id="refs" custom-style="Bibliography"></div>
\endgroup
