---
title             : "_Light Exposure Behavior Assessment (LEBA)_: Long and Short Form"
shorttitle        : "LEBA"

author: 
  - name          : "Mushfiqul Anwar Siraji"
    
    
  - name          : "Rafael Robert Lazar"
    
    
      
  - name          : "Juliëtte	van Duijnhoven"
    
    

  - name          : "Luc Schlangen"
    

  - name          : "Shamsul Haque"
    
    
      
  - name          : "Vineetha Kalavally"
    
    
      
  - name          : "Céline Vetter"
    
   
  - name          : "Gena Glickman"
    
      
  - name          : "Karin Smolders"
    
   

  - name          : "Manuel Spitschan"
    corresponding : yes

floatsintext      : yes
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no
documentclass     : "apa6"
classoption       : "man"
output            : 
  papaja::apa6_pdf:
    latex_engine: xelatex
mainfont: Helvetica
---

```{r include=FALSE}
library(Hmisc)
knitr::opts_chunk$set(warning = F, error = F, message = F, echo=FALSE)
data <- readRDS("leba_2021-09-08.rds")
sem.data <- data[, 9:56] 
prefix <- "item"
sufix <- c(1:48)
colnam <- paste(prefix,sufix, sep = "" )
colnames(sem.data) <- colnam
```

**Disclaimer**: This is a non-public version.

LEBA captures light exposure-related behaviours on a 5 point Likert type scale ranging from 1 to 5 (Never =1; Rarely= 2; Sometimes =3; Often = 4; Always =5). The score of each factor is calculated by the summation of scores of items belonging to the corresponding factor.

| Long Form (23 Items)       |
|----------------------------|
| **F1: Blue Filter**        |
| `r label(sem.data$item16)` |
| `r label(sem.data$item17)` |
| `r label(sem.data$item36)` |
| **F2: Natural Light**      |
| `r label(sem.data$item8)`  |
| `r label(sem.data$item10)` |
| `r label(sem.data$item9)`  |
| `r label(sem.data$item11)` |
| `r label(sem.data$item12)` |
| `r label(sem.data$item7)`  |
| **F3: Smart Device**       |
| `r label(sem.data$item27)` |
| `r label(sem.data$item3)`  |
| `r label(sem.data$item40)` |
| `r label(sem.data$item30)` |
| `r label(sem.data$item41)` |
| **F4: Sleep Environment**  |
| `r label(sem.data$item32)` |
| `r label(sem.data$item35)` |
| `r label(sem.data$item38)` |
| `r label(sem.data$item33)` |
| **F5: Electric Light**     |
| `r label(sem.data$item46)` |
| `r label(sem.data$item45)` |
| `r label(sem.data$item25)` |
| `r label(sem.data$item4)`  |
| `r label(sem.data$item1)`  |

\newpage

| Short Form (17 Items)      |
|----------------------------|
| **F1: Blue Filter**        |
| `r label(sem.data$item16)` |
| `r label(sem.data$item17)` |
| `r label(sem.data$item36)` |
| **F2: Natural Light**      |
| `r label(sem.data$item8)`  |
| `r label(sem.data$item10)` |
| `r label(sem.data$item11)` |
| `r label(sem.data$item12)` |
| `r label(sem.data$item7)`  |
| **F3: Smart Device**       |
| `r label(sem.data$item27)` |
| `r label(sem.data$item3)`  |
| `r label(sem.data$item40)` |
| **F4: Sleep Environment**  |
| `r label(sem.data$item32)` |
| `r label(sem.data$item35)` |
| `r label(sem.data$item33)` |
| **F5: Electric Light**     |
| `r label(sem.data$item46)` |
| `r label(sem.data$item45)` |
| `r label(sem.data$item4)`  |
