
```{r configure, include=FALSE}
library(Hmisc)
data <- readRDS("leba_2021-09-08.rds")
sem.data <- data[, 9:56] 
prefix <- "item"
sufix <- c(1:48)
colnam <- paste(prefix,sufix, sep = "" )
colnames(sem.data) <- colnam
```

\newpage
**Disclaimer**: This is a non-public version of LEBA (dated \today) and still a work in progress. Please do not distribute!

LEBA captures light exposure-related behaviours on a 5 point Likert type scale ranging from 1 to 5 (Never = 1; Rarely = 2; Sometimes = 3; Often = 4; Always = 5). The score of each factor is calculated by the summation of scores of items belonging to the corresponding factor. 

\blandscape

# LEBA Long Form (23 Items)
"Please indicate how often you performed the following behaviours in the **past 4 weeks.**"

|     | Items                      | Never | Rarely | Sometimes | Often | Always |
|-----|----------------------------|-------|--------|-----------|-------|--------|
| 1   | `r label(sem.data$item16)` |       |        |           |       |        |
| 2   | `r label(sem.data$item17)` |       |        |           |       |        |
| 3   | `r label(sem.data$item36)` |       |        |           |       |        |
| 4   | `r label(sem.data$item8)`  |       |        |           |       |        |
| 5   | `r label(sem.data$item10)` |       |        |           |       |        |
| 6   | `r label(sem.data$item9)`  |       |        |           |       |        |
| 7   | `r label(sem.data$item11)` |       |        |           |       |        |
| 8   | `r label(sem.data$item12)` |       |        |           |       |        |
| 9   | `r label(sem.data$item7)`  |       |        |           |       |        |
| 10  | `r label(sem.data$item27)` |       |        |           |       |        |
| 11  | `r label(sem.data$item3)`  |       |        |           |       |        |
| 12  | `r label(sem.data$item40)` |       |        |           |       |        |
| 13  | `r label(sem.data$item30)` |       |        |           |       |        |
| 14  | `r label(sem.data$item41)` |       |        |           |       |        |
| 15  | `r label(sem.data$item32)` |       |        |           |       |        |
| 16  | `r label(sem.data$item35)` |       |        |           |       |        |
| 17  | `r label(sem.data$item38)` |       |        |           |       |        |
| 18  | `r label(sem.data$item33)` |       |        |           |       |        |
| 19  | `r label(sem.data$item46)` |       |        |           |       |        |
| 20  | `r label(sem.data$item45)` |       |        |           |       |        |
| 21  | `r label(sem.data$item25)` |       |        |           |       |        |
| 22  | `r label(sem.data$item4)`  |       |        |           |       |        |
| 23  | `r label(sem.data$item1)`  |       |        |           |       |        |

\elandscape

\newpage

\blandscape

## Latent Structure, and Reliability

The long form of LEBA consists 23 items with five factors.

| Factor names                                      | Items                    | Reliability Coefficients: ordinal alpha |
|---------------------------------------------------|--------------------------|-----------------------------------------|
| F1: Wearing blue light filters                    | 1-3                      | .96                                     |
| F2: Spending time outdoors                        | 4-9 (Item 4 is reversed) | .83                                     |
| F3: Using phone and smartwatch in bed             | 10-14                    | .70                                     |
| F4: Using light before bedtime                    | 15-18                    | .69                                     |
| F5: Using light in the morning and during daytime | 19-23                    | .52                                     |
| McDonald's Omega coefficient for the total scale  |                          | .73 (Total scale)                       |

LEBA -long form showed satisfactory structural validity (CFI =.97; TLI = .96; RMSEA = .05 [.04-.06, 90% CI]; SRMR = .09).


\elandscape

\newpage

\blandscape

# LEBA Short Form (18 Items)

"Please indicate how often you performed the following behaviours in the **past 4 weeks.**"


|     | Short Form (18 Items)      | Never | Rarely | Sometimes | Often | Always |
|-----|----------------------------|-------|--------|-----------|-------|--------|
| 01  | `r label(sem.data$item16)` |       |        |           |       |        |
| 02  | `r label(sem.data$item17)` |       |        |           |       |        |
| 03  | `r label(sem.data$item36)` |       |        |           |       |        |
| 04  | `r label(sem.data$item8)`  |       |        |           |       |        |
| 05  | `r label(sem.data$item9)`  |       |        |           |       |        |
| 06  | `r label(sem.data$item10)` |       |        |           |       |        |
| 07  | `r label(sem.data$item11)` |       |        |           |       |        |
| 08  | `r label(sem.data$item12)` |       |        |           |       |        |
| 09  | `r label(sem.data$item7)`  |       |        |           |       |        |
| 10  | `r label(sem.data$item27)` |       |        |           |       |        |
| 11  | `r label(sem.data$item3)`  |       |        |           |       |        |
| 12  | `r label(sem.data$item40)` |       |        |           |       |        |
| 13  | `r label(sem.data$item32)` |       |        |           |       |        |
| 14  | `r label(sem.data$item35)` |       |        |           |       |        |
| 15  | `r label(sem.data$item33)` |       |        |           |       |        |
| 16  | `r label(sem.data$item46)` |       |        |           |       |        |
| 17  | `r label(sem.data$item45)` |       |        |           |       |        |
| 18  | `r label(sem.data$item4)`  |       |        |           |       |        |

\elandscape

\newpage

\blandscape

## Latent Structure

The short form of LEBA consists 23 items with five factors.

| Factor names                                          | Items                    |
|-------------------------------------------------------|--------------------------|
| **F1: Wearing blue light filters**                    | 1-3                      |
| **F2: Spending time outdoors**                        | 4-8 (Item 4 is reversed) |
| **F3: Using phone and smart-watch in bed**            | 9-11                     |
| **F4: Using light before bedtime**                    | 12-14                    |
| **F5: Using light in the morning and during daytime** | 15-17                    |


## How to cite:

\elandscape

\newpage

